package com.smartshop.ui.theme

import androidx.compose.ui.graphics.Color

val BackgroundLight = Color(0xFFF8F8F8)
val BackgroundDark = Color(0xFF1C1C1C)

val Light = Color(0xFFF8F8F8)
val Dark = Color(0xFF1C1C1C)

val BackgroundBottomMenuLight = Color(0xFFFFFFFF)
val BackgroundBottomMenuDark = Color(0x1C1C1C)

val BlueLight = Color(0xFF2580EC)
val LightBlueLight = Color(0xFFE4F0FE)
val GreenLight = Color(0xFF2B9C1C)
val BlackLight = Color(0xFF1F1F1F)
val WhiteLight = Color(0xFFD3D3D3)
val BlackWhiteDark = Color(0xFFFFFFFF)
val WhiteBlackDark = Color(0xFF000000)
val FullWhite = Color(0xFFFFFFFF)
val DarkGrayLight = Color(0xFF7B7D7F)
val LightGrayLight = Color(0xFFE9E9E9)

val BtnAddBackgroundLight = Color(0xFF2182F5)
val BtnSuggestionBackgroundLight = Color(0xFF2BBFBFBF)
val BtnAddTextLight = Color(0xFFFFFFFF)
val TextLight = Color(0xFF262626)
val TextSecondaryLight = Color(0xFF818181)
val InputBackgroundLight = Color(0xFFEDEDED)
val InputPlaceholderLight = Color(0xFFBFBFBF)

val BlueDark = Color(0xFF95C2F8)
val LightBlueDark = Color(0xFF2E373E)
val GreenDark = Color(0xFF2B9C1C)
val BlackDark = Color(0xFFE6E6E6)
val WhiteDark = Color(0xFF1F1F1F)
val BlackWhiteLight = Color(0xFF000000)
val WhiteBlackLight = Color(0xFFFFFFFF)
val DarkGrayDark = Color(0xFFF8F8F8)
val LightGrayDark = Color(0xFF2C2C2C)

val BtnAddBackgroundDark = Color(0xFF353535)
val BtnSuggestionBackgroundDark = Color(0xFF353535)
val BtnAddTextDark = Color(0xFF97C2F8)
val TextDark = Color(0xFFFFFFFF)
val TextSecondaryDark = Color(0xFFA9A9A9)
val InputBackgroundDark = Color(0xFF2A2A2C)
val InputPlaceholderDark = Color(0xFFEDEDED)
val ProgressBarBackgroundDark = Color(0xFF353535)
val ProgressBarBackgroundLight = Color(0xFFF8F8F8)
val ListBackgroundDark = Color(0xFF2C2C2C)
val ListBackgroundLight = Color(0xFFFFFFFF)
val ListMenuDark = Color(0xFFC4C4C4)
val ListMenuLight = Color(0xFF919191)
val TextThirdLight = Color(0xFF343434)
val TextThirdDark = Color(0xFFD3D3D3)
val BtnSaveBackgroundLight = Color(0xFF2B9C1C)
val BtnSaveBackgroundDark = Color(0xFF353535)
val BtnSaveTextLight = Color(0xFFFFFFFF)
val BtnSaveTextDark = Color(0xFF2B9C1C)

val BlueSky = Color(0xFF70AEF5)
val Red = Color(0xFFBF2E1C)

